# Generated by Django 3.1.7 on 2021-03-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210306_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vites_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_for',
            field=models.IntegerField(default=0),
        ),
    ]
