# Generated by Django 3.1.7 on 2021-03-08 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210307_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
